### ISSUE TITLE
Rejected discs with cd-info-status: -99 

### ISSUE THREAD

**Issue by darcyruppert** [KBNLresearch/iromlab#114]
Hi, [I've reached out to you before](https://github.com/KBNLresearch/iromlab/issues/109) and I'm currently running into another, less significant problem as I work with IROMLAB. As I run a batch of discs, I will have several logged as success=FALSE with no images created. When I look at the batch log, it reports "cd-info-status: -99" and "ERROR - Unable to identify disc type" before rejecting. It works just fine to explore these same discs on their own using Windows File Explorer or Isobuster, so I'm trying to figure out why IROMLAB is skipping over them. As an example, a CD-R I have been testing that is having this issue is single-session with three file systems identified by Isobuster -- ISO, HFS+, and Joliet. Thanks so much for any insight you can provide.

**Comment by bitsgalore** [comment]
Hi @darcyruppert. The problem you're encountering happens because for some reason the [cd-info](https://manpages.ubuntu.com/manpages/oracular/en/man1/cd-info.1.html) tool failed on those discs. This tool reports all sorts of info about the disc, such as whether it contains data or audio, the number of sessions, etc.

Iromlab needs this information to figure out how to process the disc (e.g. start IsoBuster to extract the data, start dbPoweramp to rip the audio tracks, or both). If cd-info fails,  this information is not available, and as a result Iromlab won't be able to further process the disc.

I've run into this problem myself once or twice (from what I recall the cause was some seriously damaged disc). But from what I understand you're getting this problem with multiple discs, which is a bit odd.

Are all of the affected discs CD-Rs? One thing I could imagine is you might be dealing with multiple CD-Rs that have some shared fault (e.g. because of some error when they were burnt), but I'm only speculating here.

In any case, there's not much that can be done about this, I'm afraid. If it's only a small number of discs, you might try to image them manually in IsoBuster (since you mention it's able to read them).
